version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_marketplace-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.pg_data:/var/lib/postgresql/data

volumes:
  .pg_data:
